project:
  type: website
  output-dir: docs

website:
  title: "Foxmir Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd   # 这里我也帮你改成规范写法了
        text: About
      - href: tech.qmd    # 修复点 1
        text: Technology
      - href: life.qmd    # 修复点 2
        text: Life

format:
  html:
    theme: Superhero
    css: styles.css
    toc: true

listing:
  contents: publish
  sort: "date desc"
  type: default
  categories: true